# /// script
# requires-python = ">=3.12"
# dependencies = ["playwright==1.62.0"]
# ///
"""Native Keycloak qualification; run only through the owned Go harness."""
import json
import os
import re
import sys
from pathlib import Path
from urllib.parse import parse_qs, urlencode, urlparse, urlunparse

from playwright.sync_api import expect, sync_playwright

origin = os.environ["CONDUCTOR_BROWSER_WEB_URL"]
issuer = os.environ["CONDUCTOR_KEYCLOAK_ISSUER"]
password = os.environ["CONDUCTOR_KEYCLOAK_PASSWORD"]
assert urlparse(origin).scheme == "https" and urlparse(origin).hostname == "127.0.0.1"
assert urlparse(issuer).scheme == "https" and urlparse(issuer).hostname == "localhost"
phase = "start"
last_page = None
playwright_instance = None
screenshot = Path(os.environ.get("CONDUCTOR_KEYCLOAK_SCREENSHOT", "/tmp/conductor-keycloak-workbench.png"))


def api(page, path, body=None, method="GET", workspace="team", repository="application", csrf=None):
    result = page.evaluate("""async ([path, body, method, workspace, repository, captured]) => {
        const session = captured ?? (await (await fetch('/api/v1/auth/session')).json()).csrfToken;
        const headers = {'X-Conductor-CSRF': session, 'X-Conductor-Workspace': workspace, 'X-Conductor-Repository': repository};
        if(body !== null) headers['Content-Type']='application/json';
        const response=await fetch(path,{method,headers,body:body===null?undefined:JSON.stringify(body)});
        return {status:response.status,body:await response.json()};
    }""", [path, body, method, workspace, repository, csrf])
    return result


def sign_in(page, username, expected=True, navigate=True):
    if navigate:
        page.goto(origin + "/api/v1/auth/login")
    expect(page.locator("#username")).to_be_visible()
    page.locator("#username").fill(username)
    page.locator("#password").fill(password)
    page.locator("#kc-login").click()
    if expected:
        expect(page.locator(".signed-in-identity")).to_contain_text("person-" + username)
    else:
        expect(page.get_by_role("heading", name="Sign-in could not be completed", exact=True)).to_be_visible()


def select_package(page, change_id):
    page.get_by_label("Workspace", exact=True).select_option("team")
    page.get_by_label("Managed repository", exact=True).select_option("application")
    page.get_by_label("Change ID", exact=True).fill(change_id)
    page.get_by_role("button", name="Inspect latest revision", exact=True).click()


def main():
    global phase, last_page, playwright_instance
    playwright = sync_playwright().start()
    playwright_instance = playwright
    # Trust only the unique certificate key generated by this fixture, not
    # every untrusted certificate. Go discovery/exchange also verifies it.
    browser = playwright.chromium.launch(executable_path=os.environ.get("CONDUCTOR_CHROME", "/usr/bin/google-chrome"), headless=True,
        args=["--ignore-certificate-errors-spki-list=" + os.environ["CONDUCTOR_KEYCLOAK_SPKI"]])
    contexts = []
    errors = []
    authorizations = []
    callbacks = []
    def new_page():
        global last_page
        context = browser.new_context(viewport={"width": 1440, "height": 1100})
        contexts.append(context)
        page = context.new_page()
        page.on("pageerror", lambda error: errors.append(type(error).__name__))
        def capture(request):
            parsed = urlparse(request.url)
            assert parsed.scheme != "http", "provider qualification sent plaintext HTTP"
            if request.url.startswith(issuer + "/protocol/openid-connect/auth?"):
                query = parse_qs(parsed.query)
                assert query["response_type"] == ["code"]
                assert query["scope"] == ["openid"]
                assert query["code_challenge_method"] == ["S256"]
                assert len(query["code_challenge"][0]) == 43 and len(query["state"][0]) == 43 and len(query["nonce"][0]) == 43
                assert query["redirect_uri"] == [origin + "/api/v1/auth/callback"]
                if query["nonce"] != ["x" * 43] and query["code_challenge"] != ["x" * 43]:
                    authorizations.append(query)
            if request.url.startswith(origin + "/api/v1/auth/callback?"):
                query = parse_qs(parsed.query)
                assert query.get("iss") == [issuer]
                assert "session_state" in query and "code" in query
                callbacks.append(request.url)
        page.on("request", capture)
        last_page = page
        return context, page

    phase = "native author login"
    author_context, author = new_page()
    sign_in(author, "author")
    assert "conductor-session" not in author.evaluate("document.cookie")
    assert author.evaluate("localStorage.length + sessionStorage.length") == 0
    cookies = author_context.cookies(origin)
    session_cookie = next(c for c in cookies if c["name"] == "__Host-conductor-session")
    assert session_cookie["secure"] and session_cookie["httpOnly"] and session_cookie["sameSite"] == "Lax" and session_cookie["path"] == "/"
    assert not any(c["name"].startswith("__Host-conductor") for c in author_context.cookies(issuer))
    phase = "browser author creates shared revision"
    result = api(author, "/api/v1/changes", {"content": {"intent": {"title": "Real Keycloak shared review"}, "futureField": {"retained": True}}}, "POST")
    assert result["status"] == 201, result["status"]
    change = result["body"]
    change_id = change["id"]
    path = "/api/v1/changes/" + change_id
    assert api(author, path + "/review-requests", {"revision": 1}, "POST")["status"] == 200

    phase = "native reviewer login and inspected revision"
    reviewer_context, reviewer = new_page()
    sign_in(reviewer, "reviewer")
    select_package(reviewer, change_id)
    expect(reviewer.get_by_role("heading", name="Revision 1", exact=True)).to_be_visible()
    approve = reviewer.get_by_role("button", name="Approve inspected revision", exact=True)
    expect(approve).to_be_enabled()
    old_csrf = reviewer.evaluate("async () => (await (await fetch('/api/v1/auth/session')).json()).csrfToken")
    phase = "concurrent author edit and stale approval"
    updated = api(author, path + "/revisions", {"expectedRevision": 1, "content": {"intent": {"title": "Real provider second inspected revision"}, "futureField": {"retained": True}}}, "POST")
    assert updated["status"] == 201
    assert api(author, path + "/review-requests", {"revision": 2}, "POST")["status"] == 200
    reviewer.wait_for_load_state("networkidle")
    reads = []
    capture_read = lambda request: reads.append(request.url) if request.method == "GET" and "/api/" in request.url else None
    reviewer.on("request", capture_read)
    approve.click()
    expect(reviewer.get_by_text("Renewed inspection required.", exact=True)).to_be_visible()
    assert not reads, "approval fetched a newer revision"
    reviewer.remove_listener("request", capture_read)
    reviewer.get_by_role("button", name="Inspect latest revision", exact=True).click()
    expect(reviewer.get_by_role("heading", name="Revision 2", exact=True)).to_be_visible()
    approve.click()
    expect(reviewer.get_by_text("DESIGN APPROVED", exact=True)).to_be_visible()
    approved = api(reviewer, path)
    assert approved["status"] == 200 and approved["body"]["approved"]
    reviewer.screenshot(path=str(screenshot), full_page=True)

    phase = "agent authority comes from Conductor"
    agent_context, agent = new_page()
    sign_in(agent, "agent", expected=False)
    assert not any(c["name"] == "__Host-conductor-session" for c in agent_context.cookies(origin))
    agent.goto(origin)
    assert agent.evaluate("async () => (await fetch('/api/v1/auth/session')).status") == 401
    phase = "foreign workspace isolation"
    _, other = new_page()
    sign_in(other, "other")
    expect(other.get_by_label("Workspace", exact=True).locator("option[value='team']")).to_have_count(0)
    assert api(other, path)["status"] in {403, 404}

    phase = "Conductor logout invalidates replayed cookie"
    stale_cookie = next(c for c in reviewer_context.cookies(origin) if c["name"] == "__Host-conductor-session")
    reviewer.get_by_role("button", name="Sign out", exact=True).click()
    expect(reviewer.get_by_role("heading", name="Sign in to shared review", exact=True)).to_be_visible()
    assert reviewer.evaluate("async () => (await fetch('/api/v1/auth/session')).status") == 401
    reviewer_context.add_cookies([stale_cookie])
    assert reviewer.evaluate("async () => (await fetch('/api/v1/auth/session')).status") == 401
    # Local sign-out leaves the real provider's SSO session intact, as
    # documented. A new Conductor login is still a new code/PKCE exchange.
    reviewer.goto(origin + "/api/v1/auth/login")
    expect(reviewer.locator(".signed-in-identity")).to_contain_text("person-reviewer")
    select_package(reviewer, change_id)
    phase = "actual provider logout and account switch"
    second = reviewer_context.new_page()
    last_page = second
    second.goto(issuer + "/protocol/openid-connect/logout")
    second.locator("#kc-logout").click()
    sign_in(second, "author")
    assert api(second, path, csrf=old_csrf)["status"] == 403
    reviewer.get_by_role("button", name="Inspect latest revision", exact=True).click()
    expect(reviewer.get_by_role("heading", name="Check your access", exact=True)).to_be_visible()
    expect(reviewer.get_by_role("heading", name="Revision 2", exact=True)).to_have_count(0)
    reviewer.get_by_role("button", name="Reload session", exact=True).click()
    expect(reviewer.locator(".signed-in-identity")).to_contain_text("person-author")
    expect(reviewer.get_by_label("Workspace", exact=True)).to_have_value("")
    second.get_by_role("button", name="Sign out", exact=True).click()

    failed = {}
    for parameter in ["nonce", "code_challenge"]:
        phase = "tampered " + parameter + " rejected"
        bad_context, bad = new_page()
        # Navigate to the real authorization URL twice while keeping the
        # original Conductor challenge cookie. Redirect-chain interception can
        # miss an upstream request; explicit navigation guarantees the changed
        # nonce/challenge actually reaches Keycloak.
        bad.goto(origin + "/api/v1/auth/login")
        expect(bad.locator("#username")).to_be_visible()
        parsed = urlparse(bad.url)
        assert bad.url.startswith(issuer + "/protocol/openid-connect/auth?")
        query = parse_qs(parsed.query)
        query[parameter] = ["x" * 43]
        bad.goto(urlunparse(parsed._replace(query=urlencode(query, doseq=True))))
        sign_in(bad, "reader", expected=False, navigate=False)
        assert not any(c["name"] == "__Host-conductor-session" for c in bad_context.cookies(origin))
        bad.goto(origin + "/api/v1/auth/login")
        if bad.locator("#username").count():
            bad.locator("#username").fill("reader")
            bad.locator("#password").fill(password)
            bad.locator("#kc-login").click()
        expect(bad.locator(".signed-in-identity")).to_contain_text("person-reader")
        failed[parameter] = True

    phase = "one-use callback and identity recovery"
    # Replaying a consumed native callback cannot recreate a session.
    clean_context, clean = new_page()
    clean.goto(callbacks[0])
    expect(clean.get_by_role("heading", name="Sign-in could not be completed", exact=True)).to_be_visible()
    assert not any(c["name"] == "__Host-conductor-session" for c in clean_context.cookies(origin))
    assert len(authorizations) >= 8 and len(callbacks) >= 8 and not errors
    assert len({q["state"][0] for q in authorizations}) == len(authorizations)
    assert len({q["nonce"][0] for q in authorizations}) == len(authorizations)
    Path(os.environ["CONDUCTOR_KEYCLOAK_REPORT"]).write_text(json.dumps({"changeId": change_id, "digest": approved["body"]["revision"]["digest"], "FailedNonce": failed["nonce"], "FailedPKCE": failed["code_challenge"]}))
    browser.close()
    print("PASS: native Keycloak HTTPS login, confidential S256 code flow, nonce rejection, exact shared human review, agent denial, workspace isolation, logout, account switch, old-tab recovery and one-use callback")
    print("Screenshot: " + str(screenshot))


try:
    main()
except Exception as error:
    # Provider URLs may contain one-use codes. Keep exception URLs and raw token
    # bodies out of the test log; the synthetic screenshot shows the failed UI.
    if last_page is not None:
        try:
            last_page.screenshot(path=str(screenshot.with_name("conductor-keycloak-failure.png")), full_page=True)
        except Exception:
            pass
    message = re.sub(r"https?://\S+", "<redacted-url>", str(error).splitlines()[0] if str(error) else type(error).__name__)
    print("FAIL: Keycloak qualification at " + phase + ": " + message[:200], file=sys.stderr)
    raise SystemExit(1)

finally:
    if playwright_instance is not None:
        playwright_instance.stop()
