package agents

// Amp loads in-process plugins from ~/.config/amp/plugins/<name>/. Conductor's
// is a directory of its own there, which Install copies.

const ampDir = ".config/amp/plugins/conductor/"

var ampAssets = map[string]string{
	"amp/conductor/index.ts": `// Conductor's plugin for Amp, generated by Conductor. It tells the Conductor
// session Amp runs in when a turn ends and which tools ran. Outside a
// Conductor session conductor notify does nothing.
import { spawnSync } from "node:child_process";

const CONDUCTOR = "{{BIN}}";

function notify(args) {
  try {
    spawnSync(CONDUCTOR, ["notify", ...args], { stdio: "ignore", timeout: 10000 });
  } catch {
    // Reporting must never get in the agent's way.
  }
}

export default function (amp) {
  amp.on("agent.end", () => notify(["--state", "done"]));
  amp.on("tool.result", (event) => notify(["--event", "tool_use", "--tool", String(event?.tool ?? event?.toolName ?? "").slice(0, 200)]));
}
`,
}

func ampAdapter() Adapter {
	return Adapter{
		ID:     "amp",
		Name:   "Amp",
		Assets: ampAssets,
		Install: func(home, hooksDir string) ([]string, error) {
			return install(home, copyAssetDir(ampAssets, hooksDir, "amp/conductor/", ampDir)...)
		},
		Status: func(home string) (bool, string) {
			return fileExists(home, ampDir+"index.ts")
		},
		Snippet: func(hooksDir string) string {
			return snippetOf(ampAssets, hooksDir, "amp/conductor/index.ts")
		},
		Events: []string{"done", "tool_use"},
	}
}
