package agents

// DeepSeek Harness takes TUI plugins, but it is a developer preview whose
// plugin interface still changes: Conductor generates the plugin and leaves
// installing it to the user, and the Events page marks it experimental.

var dshAssets = map[string]string{
	"dsh-conductor.js": `// Conductor's plugin for DeepSeek Harness (developer preview), generated by
// Conductor. It tells the Conductor session dsh runs in when a session
// completes or fails and when dsh asks a question or for a permission. Outside
// a Conductor session conductor notify does nothing.
import { spawnSync } from "node:child_process";

const CONDUCTOR = "{{BIN}}";

const short = (value, fallback) => String(value || fallback).slice(0, 200);

function notify(args) {
  try {
    spawnSync(CONDUCTOR, ["notify", ...args], { stdio: "ignore", timeout: 10000 });
  } catch {
    // Reporting must never get in the agent's way.
  }
}

export default function (dsh) {
  dsh.on("session-completed", () => notify(["--state", "done"]));
  dsh.on("session-failed", (event) => notify(["--event", "error", "--message", short(event?.error?.message ?? event?.error, "the session failed")]));
  dsh.on("question-asked", (event) => notify(["--state", "needs_input", "--message", short(event?.question, "DeepSeek Harness has a question")]));
  dsh.on("permission-requested", (event) => notify(["--state", "needs_input", "--message", short(event?.title, "DeepSeek Harness asks for permission")]));
}
`,
}

func dshAdapter() Adapter {
	return Adapter{
		ID:     "dsh",
		Name:   "DeepSeek Harness",
		Assets: dshAssets,
		Install: func(home, hooksDir string) ([]string, error) {
			return nil, byHand("DeepSeek Harness is a developer preview whose plugin interface still changes; add Conductor's plugin from the snippet to dsh yourself")
		},
		Snippet: func(hooksDir string) string {
			return snippetOf(dshAssets, hooksDir, "dsh-conductor.js")
		},
		Events: []string{"needs_input", "done", "error", "experimental"},
	}
}
