package agents

import "regexp"

// OpenCode loads plugins from the plugins/ directory of its config dir. At
// launch OPENCODE_CONFIG_DIR=<hooks dir>/opencode would load Conductor's, but
// only if that directory adds to the default config dir instead of replacing
// it, which is still to be verified (docs/features.md): until then there is no
// launch route, and Install copies the plugin into ~/.config/opencode/plugins.

const opencodePlugin = ".config/opencode/plugins/conductor.ts"

var opencodeAssets = map[string]string{
	"opencode/plugins/conductor.ts": `// Conductor's plugin for OpenCode, generated by Conductor. It tells the
// Conductor session OpenCode runs in when OpenCode asks for a permission, goes
// idle, runs a tool or fails. Outside a Conductor session conductor notify
// does nothing.
const CONDUCTOR = "{{BIN}}";

const short = (value, fallback) => String(value || fallback).slice(0, 200);

export const ConductorPlugin = async ({ $ }) => {
  const notify = async (args) => {
    try {
      await $` + "`${CONDUCTOR} notify ${args}`" + `.quiet().nothrow();
    } catch {
      // Reporting must never get in the agent's way.
    }
  };
  return {
    event: async ({ event }) => {
      const props = event?.properties ?? {};
      switch (event?.type) {
        case "permission.asked":
          await notify(["--state", "needs_input", "--message", short(props.title, "OpenCode asks for permission")]);
          break;
        case "session.idle":
          await notify(["--state", "done"]);
          break;
        case "tool.execute.after":
          await notify(["--event", "tool_use", "--tool", short(props.tool, "")]);
          break;
        case "session.error":
          await notify(["--event", "error", "--message", short(props.error?.data?.message ?? props.error?.name, "OpenCode reported an error")]);
          break;
      }
    },
  };
};
`,
}

func opencodeAdapter() Adapter {
	return Adapter{
		ID:   "opencode",
		Name: "OpenCode",
		// OpenCode prints its version alone (from its docs; verify).
		Probe:  &Probe{Args: []string{"--version"}, Match: regexp.MustCompile(`(?m)^\s*(?:opencode\s+)?v?(\d+\.\d+\.\d+)\s*$`)},
		Assets: opencodeAssets,
		Install: func(home, hooksDir string) ([]string, error) {
			return install(home, copyAsset(opencodeAssets, hooksDir, "opencode/plugins/conductor.ts", opencodePlugin))
		},
		Status: func(home string) (bool, string) {
			return statusOf(home, opencodePlugin, copyAsset(opencodeAssets, "", "opencode/plugins/conductor.ts", opencodePlugin))
		},
		Snippet: func(hooksDir string) string {
			return snippetOf(opencodeAssets, hooksDir, "opencode/plugins/conductor.ts")
		},
		Events: []string{"needs_input", "done", "tool_use", "error"},
	}
}
