package agents

import (
	"path/filepath"

	"github.com/phenixrizen/conductor/internal/catalog"
)

// pi loads an extension named with --extension, so a session launched by
// Conductor gets its extension from the hooks dir; Install copies it into
// ~/.pi/agent/extensions, which pi loads on every start. oh-my-pi runs the
// same extension (see omp.go).

const piExtension = ".pi/agent/extensions/conductor.ts"

// piScript is the extension for pi and oh-my-pi: it reports the end of each
// turn and every tool result.
const piScript = `// Conductor's extension for pi and oh-my-pi, generated by Conductor. It tells
// the Conductor session the agent runs in when a turn ends and which tools
// ran. Outside a Conductor session conductor notify does nothing.
import { spawn } from "node:child_process";

const CONDUCTOR = "{{BIN}}";

// Fire and forget: the agent never waits for Conductor, however slow or far
// away the server is.
function notify(args) {
  try {
    const child = spawn(CONDUCTOR, ["notify", ...args], { detached: true, stdio: "ignore" });
    child.on("error", () => {});
    child.unref();
  } catch {
    // Reporting must never get in the agent's way.
  }
}

export default function (pi) {
  pi.on("agent_end", () => notify(["--state", "done"]));
  pi.on("tool_result", (event) => notify(["--event", "tool_use", "--tool", String(event?.toolName ?? "").slice(0, 200)]));
}
`

var piAssets = map[string]string{"pi-conductor.ts": piScript}

func piAdapter() Adapter {
	return Adapter{
		ID:     "pi",
		Name:   "pi",
		Assets: piAssets,
		Inject: func(hooksDir string, sig catalog.Signal) ([]string, map[string]string) {
			return []string{"--extension", filepath.Join(hooksDir, "pi-conductor.ts")}, nil
		},
		Install: func(home, hooksDir string) ([]string, error) {
			return install(home, copyAsset(piAssets, hooksDir, "pi-conductor.ts", piExtension))
		},
		Status: func(home string) (bool, string) {
			return statusOf(home, piExtension, copyAsset(piAssets, "", "pi-conductor.ts", piExtension))
		},
		Snippet: func(hooksDir string) string {
			return snippetOf(piAssets, hooksDir, "pi-conductor.ts")
		},
		Events: []string{"done", "tool_use"},
	}
}
